---
# Manual resource - Models fromBody is manually configured to support default_action attribute.
name: Application Aware Routing Policy Definition
rest_endpoint: /template/policy/definition/approute/
has_version: true
id_attribute: definitionId
type_value: appRoute
doc_category: (Classic) Centralized Policies
attributes:
  - model_name: type
    type: String
    value: appRoute
  - model_name: name
    tf_name: name
    type: String
    mandatory: true
    description: The name of the policy definition
    example: Example
  - model_name: description
    tf_name: description
    type: String
    mandatory: true
    description: The description of the policy definition
    example: My description
  - model_name: sequences
    tf_name: sequences
    type: List
    mandatory: true
    description: List of sequences
    attributes:
      - model_name: sequenceId
        tf_name: id
        type: Int64
        mandatory: true
        id: true
        description: Sequence ID
        example: 1
      - model_name: sequenceName
        tf_name: name
        type: String
        mandatory: true
        id: true
        description: Sequence name
        example: Region1
      - model_name: sequenceType
        type: String
        value: appRoute
      - model_name: sequenceIpType
        tf_name: ip_type
        type: String
        enum_values: [ipv4, ipv6, all]
        description: Sequence IP type, either `ipv4`, `ipv6` or `all`
        example: ipv4
      - model_name: entries
        data_path: [match]
        tf_name: match_entries
        type: Set
        description: List of match entries
        attributes:
          - model_name: field
            tf_name: type
            type: String
            id: true
            mandatory: true
            enum_values:
              [
                appList,
                dnsAppList,
                dns,
                dscp,
                plp,
                protocol,
                sourceDataPrefixList,
                sourceIp,
                sourcePort,
                destinationDataPrefixList,
                destinationIp,
                destinationRegion,
                destinationPort,
                trafficTo,
                icmpMessage,
              ]
            description: Type of match entry
            example: appList
          - model_name: ref
            tf_name: application_list_id
            conditional_attribute:
              conditions:
                - name: type
                  value: appList
            type: String
            description: Application list ID
            example: e3aad846-abb9-425f-aaa8-9ed17b9c8d7c
            test_value: sdwan_application_list_policy_object.test.id
          - tf_name: application_list_version
            tf_only: true
            type: Version
            description: Application list version
            exclude_test: true
          - model_name: ref
            tf_name: dns_application_list_id
            conditional_attribute:
              conditions:
                - name: type
                  value: dnsAppList
            type: String
            description: DNS Application list ID
            example: e3aad846-abb9-425f-aaa8-9ed17b9c8d7c
            exclude_test: true
          - tf_name: dns_application_list_version
            tf_only: true
            type: Version
            description: DNS Application list version
            exclude_test: true
          - model_name: value
            tf_name: icmp_message
            conditional_attribute:
              conditions:
                - name: type
                  value: icmpMessage
            type: String
            description: ICMP Message
            exclude_test: true
            example: "echo echo-reply"
          - model_name: value
            tf_name: dns
            conditional_attribute:
              conditions:
                - name: type
                  value: dns
            type: String
            enum_values: [request, response]
            description: DNS request or response
            example: request
            exclude_test: true
          - model_name: value
            tf_name: dscp
            conditional_attribute:
              conditions:
                - name: type
                  value: dscp
            type: String
            model_type_string: true
            description: DSCP value
            example: 46
            exclude_test: true
          - model_name: value
            tf_name: plp
            conditional_attribute:
              conditions:
                - name: type
                  value: plp
            type: String
            enum_values: [low, high]
            description: PLP
            example: low
            exclude_test: true
          - model_name: value
            tf_name: protocol
            conditional_attribute:
              conditions:
                - name: type
                  value: protocol
            type: String
            description: IP Protocol, 0-255 (Single value or multiple values separated by spaces)
            example: 10
            exclude_test: true
          - model_name: ref
            tf_name: source_data_prefix_list_id
            conditional_attribute:
              conditions:
                - name: type
                  value: sourceDataPrefixList
            type: String
            description: Source Data Prefix list ID
            example: 7d97276b-321c-4d0c-870e-342bbcd51011
            exclude_test: true
          - tf_name: source_data_prefix_list_version
            tf_only: true
            type: Version
            description: Source Data Prefix list version
            exclude_test: true
          - model_name: value
            tf_name: source_ip
            conditional_attribute:
              conditions:
                - name: type
                  value: sourceIp
            type: String
            description: Source IP
            example: 10.0.0.0/12
            exclude_test: true
          - model_name: value
            tf_name: source_port
            conditional_attribute:
              conditions:
                - name: type
                  value: sourcePort
            type: String
            description: Source port, 0-65535 (Single value, range or multiple values separated by spaces)
            example: 10
            exclude_test: true
          - model_name: ref
            tf_name: destination_data_prefix_list_id
            conditional_attribute:
              conditions:
                - name: type
                  value: destinationDataPrefixList
            type: String
            description: Destination Data Prefix list ID
            example: 7d97276b-321c-4d0c-870e-342bbcd51011
            exclude_test: true
          - tf_name: destination_data_prefix_list_version
            tf_only: true
            type: Version
            description: Destination Data Prefix list version
            exclude_test: true
          - model_name: value
            tf_name: destination_ip
            conditional_attribute:
              conditions:
                - name: type
                  value: destinationIp
            type: String
            description: Destination IP
            example: 10.0.0.0/12
            exclude_test: true
          - model_name: value
            tf_name: destination_port
            conditional_attribute:
              conditions:
                - name: type
                  value: destinationPort
            type: String
            description: Destination port, 0-65535 (Single value, range or multiple values separated by spaces)
            example: 100
            exclude_test: true
          - model_name: value
            tf_name: destination_region
            conditional_attribute:
              conditions:
                - name: type
                  value: destinationRegion
            type: String
            enum_values: [primary-region, secondary-region, other-region]
            description: Destination region
            example: primary-region
            exclude_test: true
          - model_name: value
            tf_name: traffic_to
            conditional_attribute:
              conditions:
                - name: type
                  value: trafficTo
            type: String
            enum_values: [access, core, service]
            description: Traffic to
            example: access
            exclude_test: true
      - model_name: actions
        tf_name: action_entries
        type: Set
        description: List of action entries
        attributes:
          - model_name: type
            tf_name: type
            type: String
            id: true
            mandatory: true
            enum_values:
              [backupSlaPreferredColor, count, log, slaClass, cloudSaas]
            description: Type of action entry
            example: backupSlaPreferredColor
          - model_name: parameter
            tf_name: backup_sla_preferred_color
            conditional_attribute:
              conditions:
                - name: type
                  value: backupSlaPreferredColor
            type: String
            description: Backup SLA preferred color (Single value or multiple values separated by spaces)
            example: bronze
          - model_name: parameter
            tf_name: counter
            conditional_attribute:
              conditions:
                - name: type
                  value: count
            type: String
            description: Counter name
            example: count1
            exclude_test: true
          - model_name: parameter
            tf_name: log
            conditional_attribute:
              conditions:
                - name: type
                  value: log
            type: Bool
            bool_empty_string: true
            description: Enable logging
            example: true
            exclude_test: true
          - model_name: parameter
            tf_name: cloud_sla
            conditional_attribute:
              conditions:
                - name: type
                  value: cloudSaas
            type: Bool
            bool_empty_string: true
            description: Cloud SLA
            example: true
            exclude_test: true
          - model_name: parameter
            tf_name: sla_class_parameters
            conditional_attribute:
              conditions:
                - name: type
                  value: slaClass
            type: List
            description: List of SLA class parameters
            exclude_test: true
            attributes:
              - model_name: field
                tf_name: type
                type: String
                id: true
                mandatory: true
                enum_values:
                  [
                    name,
                    preferredColor,
                    preferredColorGroup,
                    strict,
                    fallbackToBestPath,
                  ]
                description: Type of SLA class parameter
                example: name
              - model_name: ref
                tf_name: sla_class_list_id
                conditional_attribute:
                  conditions:
                    - name: type
                      value: name
                type: String
                description: SLA class list ID
                example: 71920ba0-46e7-411a-a730-387414aabc08
                exclude_test: true
              - tf_name: sla_class_list_version
                tf_only: true
                type: Version
                description: SLA class list version
                exclude_test: true
              - model_name: ref
                tf_name: preferred_color_group_list_id
                conditional_attribute:
                  conditions:
                    - name: type
                      value: preferredColorGroup
                type: String
                description: Preferred color group list ID
                example: 45bd33f6-f177-42f3-8aa6-60a62dfd6dd2
                exclude_test: true
              - tf_name: preferred_color_group_list_version
                tf_only: true
                type: Version
                description: Preferred color group list version
                exclude_test: true
              - model_name: value
                tf_name: preferred_color
                conditional_attribute:
                  conditions:
                    - name: type
                      value: preferredColor
                type: String
                description: preferred color (Single value or multiple values separated by spaces)
                example: bronze
  - model_name: type
    tf_name: default_action
    data_path: [defaultAction]
    type: String
    enum_values: [slaClass]
    description: Type of default action
    exclude_test: true
    example: slaClass
  - model_name: ref
    tf_name: default_action_sla_class_list_id
    data_path: [defaultAction]
    type: String
    description: SLA class list ID
    exclude_example: true
    exclude_test: true
    conditional_attribute:
      conditions:
        - name: default_action
          value: slaClass
  - tf_name: default_action_sla_class_list_version
    tf_only: true
    type: Version 
    description: SLA class list version

test_prerequisites: |
  resource "sdwan_application_list_policy_object" "test" {
    name = "TF_TEST"
    entries = [
      {
        application = "netflix"
      }
    ]
  }
  resource "sdwan_sla_class_policy_object" "sla_test" {
    name                          = "sla_test"
    jitter                        = 100
    latency                       = 10
    loss                          = 1
  }
